[tool.poetry]
name = "nonebot_plugin_emojimix"
version = "0.1.6"
description = "Nonebot2 plugin for emojimix"
authors = ["meetwq <meetwq@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/MeetWq/nonebot-plugin-emojimix"
repository = "https://github.com/MeetWq/nonebot-plugin-emojimix"

[tool.poetry.dependencies]
python = "^3.7.3"
nonebot2 = "^2.0.0-beta.1"
nonebot-adapter-onebot = "^2.0.0-beta.1"
httpx = ">=0.19.0"
emoji = "^1.7.0"

[tool.poetry.dev-dependencies]
nb-cli = "^0.6.0"
black = "^22.1.0"

[tool.black]
line-length = 150

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
